### ISSUE TITLE
Users available as "authors"

### ISSUE THREAD

**Issue by cray74** [staskie/simple_author_change#1]
Hi,

it seems to me, the list of available authors is limited to the same group of users, which can function as "Assignees", ie. roles which have the "issues can be assigned to this role" flag. Is that correct, can that be fixed (in my understanding anybody who can create an issue should be a choice in the list of authors).

Thanks for your help (and this great plugin)!

==== Environment ====

Environment:
  Redmine version                2.4.2.stable
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  3.2.16
  Environment                    production
  Database adapter               Mysql2
SCM:
  Filesystem                     
Redmine plugins:
  a_common_libs                  0.0.1
  hooks_manager                  1.0.1
  progressive_gantt_mods         0.0.2
  redmine_agile                  1.3.1
  redmine_extended_watchers      1.0.5
  redmine_image_clipboard_paste  1.0.0
  redmine_ldap_sync              2.0.3.devel
  redmine_local_avatars          0.1.1
  redmine_my_page_queries        2.1.6
  redmine_silencer               0.4.0
  simple_author_change           0.0.1
  unread_issues                  0.0.1

===================

Kind regards,

Dietmar

**Comment by staskie** [comment]
Fixed here: 77f60c9
