### ISSUE TITLE
Error when changing Author

### ISSUE THREAD

**Issue by ElskerDane** [staskie/simple_author_change#10]
When creating an issue, I have no problems selecting a different author.

However, if I try to edit the issue and then change the author, I receive a "HTTP 404 Not Found" Error.  

![simpleauthorchangeerror3](https://cloud.githubusercontent.com/assets/12851016/10542522/b3a23c90-73e6-11e5-832f-0716105d136d.PNG)

![simpleauthorchangeerror4](https://cloud.githubusercontent.com/assets/12851016/10542524/b8c74cc4-73e6-11e5-9a3c-16abdbb4a185.PNG)

![simpleauthorchangeerror5](https://cloud.githubusercontent.com/assets/12851016/10542529/bbd670ca-73e6-11e5-89bf-aee62ac370d8.PNG)

This is what I see my production log:

![simpleauthorchangeerror](https://cloud.githubusercontent.com/assets/12851016/10542220/ad0537e0-73e4-11e5-9a92-31ae5c029c4f.PNG)

Looking at the error, I thought that perhaps I was assigning a non-project user to the issue, but I double checked, and the user I was attempting to change to is included as a member of the project.

![simpleauthorchangeerror2](https://cloud.githubusercontent.com/assets/12851016/10542455/4ea9d384-73e6-11e5-895d-5fe8057d605d.PNG)

Also, I am running Redmine 3.0.3 on a Windows Virtual Machine.

**Comment by Elkander** [comment]
I’ve got the same problem. I can change the author of a new ticket, but not of an existing one.

Running Redmine 3.0.1.stable on Ubuntu

**Comment by staskie** [comment]
I managed to reproduce this problem, but would need to trace the reason of it as it happens in the deep internals of Redmine.

**Comment by MikeschTheCat** [comment]
I have the same Problem on Redmine Version 3.1.1 (Ubuntu).

Thanks for looking in the deep ;-)

**Comment by eurodba** [comment]
Dear Dominik Staskiewicz,

I confirm that I have the same issue as other guys who post to the current issue (my Redmine is 3.2.0.stable). And IMHO, issue is very simple and clear - from the production.log:

  Rendered mailer/issue_edit.html.erb within layouts/mailer (8.4ms)
Completed 500 Internal Server Error in 578ms (ActiveRecord: 361.4ms)

    ActiveRecord::RecordNotFound (Couldn't find User with 'id'=TestUser [WHERE `users`.`type` IN ('User', 'AnonymousUser')]):
    lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
    lib/redmine/hook.rb:61:in `each'
    lib/redmine/hook.rb:61:in `block in call_hook'
    lib/redmine/hook.rb:58:in `tap'

So, you select from the USERS table incorrect column (LOGIN instead of ID) and use retrieved value in the WHERE clause of SQL query. As a result, query failed, as ID=<string> can't work :)

IMHO (I am far-far from Ruby and ROR).

Thanks in advance and it will really great, if you or someone else can pull necessary fix.


Rostislav

**Comment by danaivehr** [comment]
Thank you for your plugin, it is really helpful and musthave.

Anyway I can confirm the same issue.

Is there any chance to have it fixed for Redmine 3?

**Comment by staskie** [comment]
I just pushed a small change to deal with the problem. Would you be able to give it a try and let me know if it woks for you now?

**Comment by Elkander** [comment]
I just installed your updated plugin. And it is working perfectly. Thanx for fixing the problem.

Redmine version 3.0.1.stable

**Comment by staskie** [comment]
Thanks @Elkander for confirmation.

**Comment by danaivehr** [comment]
I can confirm this fix too. Thank you!

**Comment by eurodba** [comment]
I confirm too - all is working fine now, error is fixed!!
Big-big thanks!

P.S. I was almost created my own fix, but it's better of course, if fix is made by Author!
