### ISSUE TITLE
getting 404

### ISSUE THREAD

**Issue by dannydulai** [staskie/simple_author_change#2]
after adding this to redmine 2.5.1, i get 404 on all issues. here is the the relevant production.log:

Processing by IssuesController#show as HTML
  Parameters: {"id"=>"10474"}
  Current user: danny (id=3)
  Rendered issues/_action_menu.html.erb (2.7ms)
  Rendered issue_relations/_form.html.erb (1.2ms)
  Rendered issues/_relations.html.erb (2.2ms)
  Rendered issues/_action_menu.html.erb (2.0ms)
  Rendered issues/_form.html.erb (50.7ms)
  Rendered issues/_edit.html.erb (51.4ms)
  Rendered issues/show.html.erb within layouts/base (72.3ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.1ms)
Completed 404 Not Found in 311.4ms (Views: 12.6ms | ActiveRecord: 1.7ms)

deleting the plugin makes all issues show up.

**Comment by staskie** [comment]
Hi Danny,

I am able to successfully install and use this plugin with version 2.5.1. Have you restarted your Redmine server after installing the plugin?

Also, would you be able to paste the info from Administration -> Informaiton ?

The production log in this case doesn't say much, unfortunately.

Thanks

**Comment by dannydulai** [comment]
I tried to upgrade to 2.6.2, and I'm getting the same stuff.

I'm running the code from master. after restarting, i see the plugin as active in the plugins page on the redmine admin area.

Here is the admin->info (after I've uninstalled your plugin -- i can't install it now since the server is in use)

Default administrator account changed	True
Attachments directory writable	True
Plugin assets directory writable (./public/plugin_assets)	True
RMagick available (optional)	Exclamation
ImageMagick convert available (optional)	Exclamation

Environment:
  Redmine version                2.6.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               SQLite
SCM:
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_slack                  0.1

**Comment by staskie** [comment]
Hi Danny,

I exactly copied the setup you have and still I wasn't able to reproduce the error. Sorry.

What you can do is you can set up a more verbose logging in your production environment and then send me the log. 

You could do this in config/dditional_environment.rb file with:

```ruby
config.log_level = :warn
```
And restart the server.

**Comment by dannydulai** [comment]
OK, I found a fix. I had to do this the below to get it to work. Any ideas on how to not need this hack? My rails knowledge is weak.

```
redmine-2.6.2 # mv plugins/redmine_change_issue_author/app/views/issues/_simple_author_change.html.erb app/views/issues/
```

it should be noted that there is 1 comment on http://www.redmine.org/plugins/simple_author_change for this plugin, and it looks like this person is having the same problem I am.

**Comment by staskie** [comment]
Hi Danny,

Aaahh.... okay, I think all is clear to me now.

You have got the plugin installed in the wrong directory. The plugin needs to be in:

```bash
plugins/simple_author_change
```

Otherwise Redmine can't find the _simple_author_change.html.erb file.

To get this fixed, you would need to:

* Move the file back:

```bash
mv app/views/issues/_simple_author_change.html.erb plugins/redmine_change_issue_author/app/views/issues
```
* Rename the folder to the correct name:

```bash
mv plugins/redmine_change_issue_author plugins/simple_author_change
```

I will update the description on the plugins installation page to make it clear. 

Let me know if it worked.

Thanks

**Comment by dannydulai** [comment]
that worked. thanks! iin retrospect, it was an obvious issue. but in reality, for some reason, it was unclear where these plugins go
