### ISSUE TITLE
Only members showing up

### ISSUE THREAD

**Issue by aleksandervines** [staskie/simple_author_change#4]
Hi,

I'm not sure if its related to issue #1 or not, I'm using the latest version from github.

I've installed the plugin, added the module to project and added rights so I can change the author.

However, In the "search for new author" field, I only find members of my group. Note: my group is the only group that is members of the project. But my project is public, and all users of the site should have access to create issues - and I'd want to be able to select "non member users" as authors.

Cheers,
Aleksander

**Comment by Q-BiC66** [comment]
I have the same issue. I can only select from Manager/Developer/Reporter roles.
In our situation, we also allow "Non Member" roles to add issues, but I cannot select them.

I had a look at lib/simple_author_change/project_patch.rb, hoping I could hack it myself, but I'm not familiar with Ruby or the Redmine API.

**Comment by staskie** [comment]
Hi guys,

Right now only users from member groups with permission `add_issue` are allowed to be set as authors.

Additionally, you can add an anonymous group to members and set the same permission for them. 

If I understand your requirements correctly, you'd like to be able to assign ANY user from the system as an author, even if she is not a member of the project. Is this correct?

Thanks

**Comment by Q-BiC66** [comment]
That is correct. I like to be able to assign ANY user with Add Issue permissions, and in our case the "Non Member" role has that permission.

We are only a small team with 5 devs and only have some internal "colleagues/customers" in our company. 
- The 5 of us are all Managers with all available permissions.
- Reporter & Developer roles are not used.
- Our customers are "Non Members" and that role has the "Add Issue" permission set.

That way any user can simply log in and immediately submit a ticket without us having to assign them to a project first...

For know I quickly hacked around it by changing
``User.where(id: permitted_user_ids).like(query).sorted``
with
``User.where('1=1').like(query).sorted``

Which is ugly as hell and also allows to select users who do NOT have permission, but I don't know anything about Ruby :p

**Comment by staskie** [comment]
Having

`User.where('1=1').like(query).sorted`

is a good start :-)

You can also try this:

https://gist.github.com/staskie/bfa1988ac5c1328de846

I haven't tested it, but there's a chance that it will do what you need.

To add this change you request to the current code base would require a bit of thinking. So maybe as a temporary solution you could change the file manually.

**Comment by Q-BiC66** [comment]
Thanks for you quick response, but your solution doesn't seem to work :/ Still doesn't show the non-members, so I'll stick with my "1=1" fix for now. :)

**Comment by staskie** [comment]
Cool, no worries :+1:
