### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by boonkerz** [staskie/simple_author_change#5]
`ActionView::Template::Error (undefined method `potential_author_name' for #<#<Class:0x0000000462bac0>:0x0000000e2e84f8>):
    1: <% if User.current.allowed_to?(:change_issue_author, @project) %>
    2:   <p>
    3:     <label for="issue_author_id"><%= l(:field_author) %><span class="required"> *</span></label>
    4:     <%= text_field_tag '', potential_author_name(@issue, params), disabled: true, style: 'margin-top:-5px', id: :issue_author_name %>
    5:     <%= hidden_field_tag 'issue[author_id]', @issue.author_id, id: :issue_author_id %>
    6:     <%= link_to image_tag('edit.png'), new_project_issue_author_path(@project), remote: true %>
    7:   </p>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/issues/_form.html.erb:2:in `block in _app_views_issues__form_html_erb__2417055906794805917_37919520'
  app/helpers/application_helper.rb:1063:in `labelled_fields_for'
  app/views/issues/_form.html.erb:1:in `_app_views_issues__form_html_erb__2417055906794805917_37919520'
  app/views/issues/_edit.html.erb:8:in `block in _app_views_issues__edit_html_erb___1111795725777668744_38433660'
  app/helpers/application_helper.rb:1056:in `labelled_form_for'
  app/views/issues/_edit.html.erb:1:in `_app_views_issues__edit_html_erb___1111795725777668744_38433660'
  app/views/issues/show.html.erb:132:in `_app_views_issues_show_html_erb___2953408940720828111_77791560'
  app/controllers/issues_controller.rb:128:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:125:in `show'`

**Comment by boonkerz** [comment]
root@341f28a04e79:/home/redmine/redmine/plugins/simple_author_change# pwd
/home/redmine/redmine/plugins/simple_author_change

**Comment by boonkerz** [comment]
`
Environment:
  Redmine version                2.6.1.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.3.8
  redmine_checklists             3.1.1
  redmine_contacts               3.4.5
  redmine_contacts_helpdesk      2.4.0
  redmine_contacts_invoices      3.3.0
  redmine_finance                1.2.1
  redmine_products               1.1.0
  simple_author_change           0.0.3
`

**Comment by staskie** [comment]
Hi @boonkerz 

The error message says: undefined method `potential_author_name`, but this method is defined here:

https://github.com/staskie/simple_author_change/blob/master/lib/simple_author_change/issues_helper_patch.rb#L8

Did you restart your Redmine after installing the plugin?

Thanks

**Comment by boonkerz** [comment]
yes

```
root@341f28a04e79:/home/redmine/redmine/plugins/simple_author_change# ll lib/simple_author_change/
hooks.rb                issue_patch.rb          issues_helper_patch.rb  project_patch.rb        
root@341f28a04e79:/home/redmine/redmine/plugins/simple_author_change# ll lib/simple_author_change/             
hooks.rb                issue_patch.rb          issues_helper_patch.rb  project_patch.rb        
root@341f28a04e79:/home/redmine/redmine/plugins/simple_author_change# cat lib/simple_author_change/              
hooks.rb                issue_patch.rb          issues_helper_patch.rb  project_patch.rb        
root@341f28a04e79:/home/redmine/redmine/plugins/simple_author_change# cat lib/simple_author_change/issues_helper_patch.rb 
module SimpleAuthorChange
  module IssuesHelperPatch
    def self.included(base)
      base.send(:include, InstanceMethods)
    end

    module InstanceMethods
      def potential_author_name(issue, params)
        if params[:issue] && params[:issue][:author_id]
          User.find(params[:issue][:author_id])
        else
          issue.author
        end
      end
    end
  end
end
root@341f28a04e79:/home/redmine/redmine/plugins/simple_author_change#
```

**Comment by quanvn** [comment]
Dear staskie, I got the same error as boonkerz, I am using redmine 2.6.4, ruby 2.0.0, rails 3.1.2 on debian 7

**Comment by staskie** [comment]
@quanvn, @boonkerz, okay - I will take another look. It may have to do something with the recent versions of Redmine.

**Comment by ffernndez** [comment]
Hello starkie, I can confirm the issue on redmine 2.6.0.stable with ruby 2.0 and rails 3.2

**Comment by BRUTEF0RCE** [comment]
Same error messages over here with Redmine 3.0.2.stable, Ruby 2.0.0-p645 (2015-04-13) [i386-mingw32] and Rails 4.2.1. I know it not in the supported redmine version list, but it is just to let you know.

**Comment by staskie** [comment]
I run this plugin with the following:

```
Environment:
  Redmine version                2.6.4.stable
  Ruby version                   2.1.2-p95 (2014-05-08) [x86_64-darwin13.0]
  Rails version                  3.2.21
  Environment                    development
  Database adapter               Mysql2
```

And was _not_ able to reproduce this problem. But I moved the method that was failing from helpers to models, so please checkout the latest code from master and let me know if this fixes the issue for you.

Make sure you restart the Redmine servers, so the new plugin version is picked up.

**Comment by ffernndez** [comment]
Hello Starkie,

Now I can change the author opening the Issue and save it. But if I change any value of the form that provoques other fields could appear, then I have this error:

```
ActionView::Template::Error (undefined local variable or method `params' for #<Issue:0x0000000254bc38>):
    1: <% if User.current.allowed_to?(:change_issue_author, @project) %>
    2:   <p>
    3:     <label for="issue_author_id"><%= l(:field_author) %><span class="required"> *</span></label>
    4:     <%= text_field_tag '', @issue.potential_author_name(params), disabled: true, style: 'margin-top:-5px', id: :issue_author_name %>
    5:     <%= hidden_field_tag 'issue[author_id]', @issue.author_id, id: :issue_author_id %>
    6:     <%= link_to image_tag('edit.png'), new_project_issue_author_path(@project), remote: true %>
    7:   </p>
```

**Comment by staskie** [comment]
Hi @ffernndez

My bad, sorry. There was an error in a model. Please checkout the latest version and try again.

Let me know how if it worked.

Thanks

**Comment by boonkerz** [comment]
for me it worked thx @staskie

**Comment by ffernndez** [comment]
Yes!! Now its working!!

Great job! thxs!!

**Comment by quanvn** [comment]
Confirm work for me on redmine 2.65, rails 3.2. Thanks @staskie
