### ISSUE TITLE
Redmine 3.0.x

### ISSUE THREAD

**Issue by KirillB09** [staskie/simple_author_change#6]
Hi
are you going to update your plugin to support Red mine 3.0.*?

Thanks for promt responce

**Comment by staskie** [comment]
Hi @KirillB09 

There is another issue #5 which I am going to fix soon. Then I will see how much work is involved in getting the plugin compatible with Redmine 3. Maybe none and after fixing it will work out of the box.

At least that's my hope, but we will see.

**Comment by staskie** [comment]
Hi @KirillB09 

The issue #5 has been fixed. Would you be able to check if the plugin now works with Redmine 3?

Thanks

**Comment by KirillB09** [comment]
Hi 
I can't pick up new auther from the list. Phehaps that's due to we use cyrilic in user name

**Comment by Elkander** [comment]
I don't think it has something to do with cyrillic characters. If I try to find an author, the ajax call will return a 500 error (url: /projects/diversen/issue_authors/autocomplete.js?q=xx)

**Comment by BRUTEF0RCE** [comment]
Hi, I do have the same problem as Elkander : 

![image](https://cloud.githubusercontent.com/assets/6563540/8779768/11dee352-2ed3-11e5-9f5e-16abc56a4580.png)

**Comment by staskie** [comment]
Hi guys,

Thanks for your feedback.

To be honest, I didn't have time to look how this plugin may work with Redmine in version 3.0. I may have a go in couple of weeks, when I have more free time.

**Comment by BRUTEF0RCE** [comment]
Ok!  Thank you for your consideration in this matter! :)

**Comment by BRUTEF0RCE** [comment]
Any news on this problem? :)

**Comment by staskie** [comment]
Hey @BRUTEF0RCE,

I just pushed some changes. Would you be able to install the plugin and test if it now works with your version of Redmine?

Thanks

**Comment by BRUTEF0RCE** [comment]
Good day @staskie ,

  2 things;

  1- when I click on the edit pen to change the author, there is still no user listed in the popup window.
  BUT...
   2- When I start typing in a few characters in the search bar, then the users appears in a list form!

For myself, it is now usable and I want to thank you for your time!

Regards.

**Comment by staskie** [comment]
Hi there,

I am glad it works for you.

What you described is a correct behaviour of the plugin to avoid loading all the users, which, depending on the system, may create some performance issues.
