### ISSUE TITLE
permition dont work

### ISSUE THREAD

**Issue by SReiver** [staskie/simple_author_change#7]
Can't change any author:
I installed plugin, add permitions "Change issue author" for all roles,
but "User.current.allowed_to?(:change_issue_author, @project)" return false always (for any users, even for redmine's admin)

Environment:
  Redmine version                2.5.3.stable
  Ruby version                   2.0.0-p598 (2014-11-13) [i686-linux]
  Rails version                  3.2.19
  simple_author_change           0.0.4

**Comment by staskie** [comment]
Hi @SReiver 

Did you enable Simple Author Change in a list of modules for a project?

Thanks

**Comment by SReiver** [comment]
No, I jast git clone and restart redmine.
Simple Author Change plugin appeared in plugins list, but don't have any settings
![sc](https://cloud.githubusercontent.com/assets/12625891/7836506/5b0ae11c-0489-11e5-8d65-3ac143df09e8.jpg)

Do I need to do something else?

**Comment by SReiver** [comment]
Sorry, i understend what does it mean "to turn on the module for your project"  just now.
Its work now.

Thank you!
