### ISSUE TITLE
Which branch to use for Redmine 2.5.1?

### ISSUE THREAD

**Issue by jmnavarrol** [staskie/simple_author_change#8]
Hi, Dominik:

I'm in the process of evaluating this Redmine plugin and I saw you recently created a 2.x branch.

Since I'm using Redmine 2.5.1, should I use the 2.x branch or am I safe using master, now and in the future?

TIA

**Comment by staskie** [comment]
Hi @jmnavarrol,

The master branch should work with Redmine 3.0 only (I am still waiting for some feedback from users before updating the README)

In your case, use Redmine-2.x branch. It was tested and proved to be working with Redmine 2.6, but should also work with 2.5.1. Let me know your feedback after the evaluation.

Thanks

**Comment by jmnavarrol** [comment]
> The master branch should work with Redmine 3.0 only

Thanks for your fast answer, @staskie.  I'll use 2.x then.

> Let me know your feedback after the evaluation.

It works as expected and I say ACLs are OK, but it still doesn't cover my current needs in full: it can change an issue's ownership, but not that of added comments.

My use case is for an end user (probably a manager) telling a developer/sysadmin to do something (by voice or email) and then the developer creates a ticket on behalf of the user.  That's the OK part but then, going down the road, the user talks to the developer or, again, sends him an email about the issue's status and there's no way for the developer to create an associated comment as if coming from the user.

**Comment by staskie** [comment]
Hi @jmnavarrol,

Thanks for the detailed explanation. I will add this feature to the todo list, but can't promise to do it soon.
