### ISSUE TITLE
Stack level too deep 

### ISSUE THREAD

**Issue by dominch** [staskie/simple_author_change#9]
Hello, 
after installation of this plugin I got constantly errors on issue edit: 

<pre>
SystemStackError in IssuesController#update

stack level too deep

Rails.root: /var/data/redmine_test
Application Trace | Framework Trace | Full Trace

actionpack (3.2.22) lib/action_dispatch/middleware/reloader.rb:70:in `rescue in call'
actionpack (3.2.22) lib/action_dispatch/middleware/reloader.rb:63:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.22) lib/rails/rack/logger.rb:32:in `call_app'
railties (3.2.22) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.22) lib/active_support/tagged_logging.rb:22:in `tagged'
railties (3.2.22) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.7) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.22) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.7) lib/rack/lock.rb:15:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/static.rb:83:in `call'
rack-mini-profiler (0.9.7) lib/mini_profiler/profiler.rb:170:in `call'
railties (3.2.22) lib/rails/engine.rb:484:in `call'
railties (3.2.22) lib/rails/application.rb:231:in `call'
railties (3.2.22) lib/rails/railtie/configurable.rb:30:in `method_missing'
passenger (5.0.5) lib/phusion_passenger/rack/thread_handler_extension.rb:85:in `process_request'
passenger (5.0.5) lib/phusion_passenger/request_handler/thread_handler.rb:155:in `accept_and_process_next_request'
passenger (5.0.5) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
passenger (5.0.5) lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
passenger (5.0.5) lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'

Request

Parameters:

{"utf8"=>"✓",
 "_method"=>"put",
 "authenticity_token"=>"tx9Dr40GNTrtTn129q8Ep3xf5rhFYAW9JZJ6VHU+l0k=",
 "issue"=>{"is_private"=>"0",
 "project_id"=>"10",
 "tracker_id"=>"2",
 "subject"=>"test",
 "description"=>"test",
 "status_id"=>"1",
 "priority_id"=>"2",
 "assigned_to_id"=>"2509",
 "parent_issue_id"=>"",
 "start_date"=>"2015-10-09",
 "due_date"=>"",
 "estimated_hours"=>"",
 "notes"=>"test ",
 "private_notes"=>"0",
 "lock_version"=>"9"},
 "time_entry"=>{"hours"=>"",
 "activity_id"=>"",
 "comments"=>""},
 "last_journal_id"=>"648",
 "commit"=>"Wyślij",
 "id"=>"1303"}

Show session dump

_csrf_token: "tx9Dr40GNTrtTn129q8Ep3xf5rhFYAW9JZJ6VHU+l0k="
atime: 1444397387
backlogs: true
ctime: 1444223372
issues_index_sort: "id:desc"
my_account_sort: "none"
query: {:project_id=>11, :filters=>{"status_id"=>{:operator=>"o", :values=>[""]}}, :group_by=>nil, :column_names=>nil}
recent_projects: [10, 11, 14]
session_id: "3f54c31a61c0e1388acb0397936b19cf"
user_id: 2509

Show env dump

HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
HTTP_ACCEPT_ENCODING: "gzip, deflate"
HTTP_ACCEPT_LANGUAGE: "pl,en-US;q=0.7,en;q=0.3"
REMOTE_ADDR: "10.2.0.22"
SERVER_NAME: "redmine-test"
SERVER_PROTOCOL: "HTTP/1.1"

Response

Headers:

None
</pre>

Redmine info: 

<pre>
Redmine 2.6.6.stable.14542
Zmieniono domyślne hasło administratora 	True
Zapisywalne repozytorium plików 	True
Zapisywalny katalog zasobów wtyczek (./public/plugin_assets) 	True
RMagick dostępne (opcjonalnie) 	True
Konwersja przez ImageMagick dostępna (optional) 	True

Environment:
  Redmine version                2.6.6.stable.14542
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux]
  Rails version                  3.2.22
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Darcs                          2.8.4
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  1.1.4
  ajax_counters                  1.1.0
  author                         0.1.0
  clipboard_image_paste          1.10
  collapsed_journals             0.0.3
  due_date_reminder              0.3.2
  enhanced_my_page               0.0.1
  extra_queries                  0.0.1
  localizable                    0.3.0
  progressive_projects_list      1.0.0
  recurring_tasks                2.0.0-pre
  redmine_another_my_projects    0.0.1
  redmine_avatar_check           0.1.0
  redmine_backlogs               v1.0.6
  redmine_banner                 0.1.1
  redmine_base_deface            0.0.1
  redmine_better_gantt_chart     0.9.0
  redmine_blocks_layout          0.0.2
  redmine_category_watchers      0.0.1
  redmine_checklists             3.0.1
  redmine_codebutton             0.1.0
  redmine_custom_css             0.1.6
  redmine_dashboard              3.0.0.dev0
  redmine_default_assign         0.4
  redmine_default_custom_query   1.1.2
  redmine_didyoumean             1.2.0
  redmine_email_fetcher          0.0.1
  redmine_embedded_video         0.1.0
  redmine_evm                    1.0.0
  redmine_evolvingweb_extensions 0.0.1
  redmine_highlightjs            1.0.3
  redmine_impasse                1.3.0
  redmine_import_issues          1.0.0
  redmine_improved_searchbox     0.0.3
  redmine_incoming_emails        0.0.1
  redmine_information            1.0.3
  redmine_inline_note_images_plugin 0.0.1
  redmine_issue_clipboard        0.1.0
  redmine_issue_completion       0.0.2
  redmine_issue_favicon          0.0.1
  redmine_issue_icons            1.0.0
  redmine_issue_reminder         0.1.0
  redmine_issue_templates        0.1.0
  redmine_knowledgebase          3.0.7
  redmine_ldap_ou_to_group       0.2
  redmine_ldap_sync              2.0.7.devel.g202f7c74b9-dirty
  redmine_lightbox               0.0.1
  redmine_login_audit            0.1.5
  redmine_logs                   0.0.5
  redmine_mail_reminder          2.6.5.0001
  redmine_maintenance_mode       2.0.1
  redmine_monitoring_controlling 0.1.1
  redmine_my_page_queries        2.1.6
  redmine_mylyn_connector        2.8.2.stable
  redmine_notified               0.0.1
  redmine_people                 0.1.8
  redmine_per_project_formatting 0.0.4
  redmine_query_share            1.0.0
  redmine_release_notes          2.0.0
  redmine_revision_diff          0.1.1
  redmine_spent_time_column      2.0.0-devel
  redmine_stats                  0.0.2
  redmine_sudo                   0.0.1
  redmine_tags                   0.1
  redmine_textiletable           0.1.0
  redmine_theme_changer          0.1.1
  redmine_timesheet_plugin       0.7.0
  redmine_tweaks                 0.5.1
  redmine_user_issues            0.0.2
  redmine_wiki_html_util         0.0.1
  redmine_wiki_issue_details     0.1.0
  redmine_wiki_lists             0.0.4
  redmine_wiki_notes             0.0.2
  redmine_work_time              0.3.0
  rm_user_mentions               0.0.1
  rmplus_devtools                1.0.0
  simple_author_change           0.0.5
  single_auth                    1.1
  status_button                  0.1.0
  subscription                   0.0.1b
  timelog_on_issue_page          0.0.1
  unread_issues                  1.5.0
  usability                      2.0.0
  view_customize                 1.1.2
  wiking                         0.0.3
</pre>

I used Redmine-2-x branch from repo, 
When plugin is removed - everything is back to normal.

**Comment by staskie** [comment]
Hi @dominch,

This plugins works well with the Redmine version you're using. The problem may be that it conflicts with one of the other plugins you're using, but I can't really tell which one.

You could try removing all other plugins (temporarily) and check if simple_author_change works with your installation.

Let me know how it goes.

Thanks

**Comment by dominch** [comment]
Hello, 
I managed to fix this error, but I'm not sure what casued conflict, most plugins were upgraded to new versions and that helped. Thanks for assistance :)
